export const types = [
  { value: "topic", label: "Topic Test" },
  { value: "section", label: "Sectional Test" },
  { value: "mockMini", label: "Mock Mini Test" },
  { value: "mockFull", label: "Mock Full Test" },
];

export const sections = [
  { value: "qa", label: "Quantitative Ability" },
  { value: "varc", label: "Verbal Ability & Reading Comprehension" },
  { value: "dilr", label: "Data Interpretation & Logical Reasoning" },
];

export const topics = {
  "qa": [
    "Profit & Loss",
    "Time & Work",
    "Time Speed & Distance",
    "Mixtures",
    "Ratio & Proportion",
    "Percentage",
    "Averages",
    "Simple & Compound Interest",
    "Chain Rule",
    "Geometry & Mensuration: Lines & Angles",
    "Circles",
    "Triangles",
    "Polygons",
    "Area & Volume of 2D and 3D figures",
    "Coordinate Geometry",
    "Quadratic Equations",
    "Series",
    "Inequalities",
    "Functions",
    "Surds & Indices",
    "Logarithm",
    "Numbers: Real Numbers",
    "Irrational Numbers",
    "Complex Numbers",
    "HCF",
    "LCM",
    "Unit’s Digit",
    "Remainders",
    "Zeroes",
    "Modern Math: Permutation and Combination",
    "Probability",
    "Set Theory",
  ],
  "varc": [
    "Para Jumbles",
    "Summary",
    "Sentence Completion",
    "Odd Sentence Out",
    "Antonyms & Synonyms",
    "Error Detection",
    "Phrase Modifiers",
    "Idioms",
    "Analogies",
    "Cloze Test",
    "Word Usage",
    "Facts-Inference-Judgement",
    "Critical Analysis of Passage",
    "Themes of the RC passage",
  ],
  "dilr": [
    "Caselets",
    "Tabular Data",
    "Pie Charts",
    "Line Graphs",
    "Bar Graphs",
    "Column Graphs",
    "Combination Graphs/Charts",
    "Syllogisms",
    "Puzzles",
    "Blood Relations",
    "Coding-Decoding",
    "Seating Arrangement",
    "Ranking",
    "Direction Sense Test",
    "Logical Sequence",
  ],
};